kind: ReplicationController
apiVersion: v1
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  replicas: 1
  selector:
    name: locust
    role: master
  template:
    metadata:
      labels:
        name: locust
        role: master
    spec:
      containers:
        - name: locust
          image: hakobera/locust:latest
          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_URL
              value: http://buildbot-master:8010
            - name: SCENARIO_FILE
              value: /test/locustfile.py
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
          volumeMounts:
            - name: locust-task-file
              mountPath: /test
      volumes:
        - name: locust-task-file
          configMap:
            name: locust-config

