apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-config
data:
  locustfile.py: |
    #!/usr/bin/env python

    import uuid

    from datetime import datetime
    from locust import HttpLocust, TaskSet, task


    class MetricsTaskSet(TaskSet):
        _deviceid = None

        def on_start(self):
            self._deviceid = str(uuid.uuid4())

        @task(999)
        def get_root(self):
            self.client.get("/")


    class MetricsLocust(HttpLocust):
        task_set = MetricsTaskSet
