#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: buildbot
#  annotations:
#    ingress.kubernetes.io/ssl-redirect: "false"
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /
#        backend:
#          serviceName: buildbot-master
#          servicePort: 8010
